import type { MissionControlShellSettingsPanelProps } from "@/components/mission-control/mission-control-shell.settings";
import type { GatewayActionGuidance } from "@/components/mission-control/settings-control-center.utils";

export type SettingsArea = "general" | "ai-tools" | "workspace" | "runtime" | "security" | "advanced";
export type GatewayControlAction = "start" | "stop" | "restart" | "doctor";
export type ToolSettingId = "browser" | "web-fetch" | "web-search";

export type SettingsPageProps = {
  sidebarOpen?: boolean;
  activeSection: SettingsArea;
  onSelectSection: (section: SettingsArea) => void;
  onOpenAdvancedSection: (section: string) => void;
  onToggleTheme: () => void;
  snapshot: MissionControlShellSettingsPanelProps["snapshot"];
  surfaceTheme: MissionControlShellSettingsPanelProps["surfaceTheme"];
  workspaceRootDraft: string;
  isSavingWorkspaceRoot: boolean;
  onWorkspaceRootDraftChange: (value: string) => void;
  onSaveWorkspaceRootSettings: (value: string | null) => Promise<void>;
  selectedModelId: string;
  onSelectedModelIdChange: (value: string) => void;
  modelOnboardingRunState: MissionControlShellSettingsPanelProps["modelOnboardingRunState"];
  onRunModelSetDefault: (modelId?: string) => Promise<void>;
  onOpenAddModels: (provider?: Parameters<MissionControlShellSettingsPanelProps["onOpenAddModels"]>[0]) => void;
  onOpenSetupWizard: MissionControlShellSettingsPanelProps["onOpenSetupWizard"];
  browserToolEnabled: boolean | null;
  webFetchToolEnabled: boolean | null;
  webSearchToolEnabled: boolean | null;
  isLoadingToolSettings: boolean;
  savingToolSettingId: ToolSettingId | null;
  toolSettingsSaveState: "idle" | "saving" | "saved" | "error";
  toolSettingsError: string | null;
  onSaveToolSetting: (settingId: ToolSettingId, enabled: boolean) => void;
  onOpenControlUi: () => Promise<void>;
  isOpeningControlUi: boolean;
  controlUiOpenError: string | null;
  isGatewayServiceOnline: boolean;
  gatewayActionGuidance: GatewayActionGuidance;
  gatewayActionBusy: boolean;
  gatewayControlAction: GatewayControlAction | null;
  onRunRecommendedGatewayAction: () => void;
  onRunGatewayControlAction: (action: GatewayControlAction) => void;
  openClawAppConnectOpen: boolean;
  onOpenClawAppConnectOpenChange: (open: boolean) => void;
  onPairingPrepared: () => void;
  onOpenUpdateDialog: MissionControlShellSettingsPanelProps["onOpenUpdateDialog"];
  onOpenResetDialog: MissionControlShellSettingsPanelProps["onOpenResetDialog"];
  isSettingsOperationInProgress: boolean;
  settingsOperationTitle: string;
  settingsOperationDescription: string;
};
